backend:
  name: github
  repo: pocka/log.pocka.io
  branch: master

publish_mode: editorial_workflow

media_folder: public/images
public_folder: /images

collections:
- name: blog
  label: Blog
  folder: posts
  create: ture
  slug: "{{name}}.md"
  fields:
  - label: Name
    name: name
    widget: string
  - label: Title
    name: title
    widget: string
  - label: Description
    name: description
    widget: string
  - label: Created At
    name: createdAt
    widget: datetime
  - label: Updated At
    name: updatedAt
    widget: datetime
  - label: Tags
    name: tags
    widget: list
    default: ['blog']
  - label: Body
    name: body
    widget: markdown
